import 'package:optivus2/models/meditation_track_model.dart';

class MeditationLibrary {
  static const List<MeditationTrack> tracks = [
    // 432 Hz / Deep Healing
    MeditationTrack(
      id: "healing_432hz_01",
      label: "432 Hz Meditation (Short, Pixabay)",
      category: "healing_432hz",
      subCategory: "deep_healing",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 175,
      durationLabel: "2:55",
      assetPath: "assets/audio/healing_432hz/healing_432hz_01.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-432-hz-meditation-short-pixabay-317516/",
      author: "Siarhei_Korbut",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 1,
    ),
    MeditationTrack(
      id: "healing_432hz_02",
      label: "Floating in Stillness. Relax instrumental Background music. Short 1",
      category: "healing_432hz",
      subCategory: "deep_healing",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 230,
      durationLabel: "3:50",
      assetPath: "assets/audio/healing_432hz/healing_432hz_02.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-floating-in-stillness-relax-instrumental-background-music-short-1-517222/",
      author: "Pink_Sound",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 2,
    ),
    MeditationTrack(
      id: "healing_432hz_03",
      label: "432 Hz (tune in with nature)",
      category: "healing_432hz",
      subCategory: "deep_healing",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 213,
      durationLabel: "3:33",
      assetPath: "assets/audio/healing_432hz/healing_432hz_03.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-432-hz-tune-in-with-nature-156265/",
      author: "NoneNothingNowhere",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 3,
    ),
    MeditationTrack(
      id: "healing_432hz_04",
      label: "Meditation Deep 432 Hz (Short, Pixabay)",
      category: "healing_432hz",
      subCategory: "deep_healing",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 168,
      durationLabel: "2:48",
      assetPath: "assets/audio/healing_432hz/healing_432hz_04.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-meditation-deep-432-hz-short-pixabay-358014/",
      author: "Siarhei_Korbut",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 4,
    ),
    MeditationTrack(
      id: "healing_432hz_05",
      label: "Calm Soul Meditation",
      category: "healing_432hz",
      subCategory: "deep_healing",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 240,
      durationLabel: "4:00",
      assetPath: "assets/audio/healing_432hz/healing_432hz_05.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-calm-soul-meditation-247330/",
      author: "Universe_Bella",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: true,
      isActive: true,
      sortOrder: 5,
    ),
    // Om / Mantra
    MeditationTrack(
      id: "healing_432hz_06",
      label: "AUM/Om Namah Shivaya Mantra Chants 432 Hz",
      category: "healing_432hz",
      subCategory: "om_mantra",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 306,
      durationLabel: "5:06",
      assetPath: "assets/audio/healing_432hz/healing_432hz_06.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-aumom-namah-shivaya-mantra-chants-432-hz-8940/",
      author: "BluBonRelaXon",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 6,
    ),
    MeditationTrack(
      id: "healing_432hz_07",
      label: "Deep Om Chants with Reverb",
      category: "healing_432hz",
      subCategory: "om_mantra",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 536,
      durationLabel: "8:56",
      assetPath: "assets/audio/healing_432hz/healing_432hz_07.mp3",
      sourceUrl: "https://pixabay.com/music/religious-theme-deep-om-chants-with-reverb-229614/",
      author: "kalsstockmedia",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: true,
      isActive: true,
      sortOrder: 7,
    ),
    MeditationTrack(
      id: "healing_432hz_08",
      label: "Free Soul Om Mantra Chants in Two Tones",
      category: "healing_432hz",
      subCategory: "om_mantra",
      displayCategory: "432 Hz / Deep Healing",
      durationSeconds: 359,
      durationLabel: "5:59",
      assetPath: "assets/audio/healing_432hz/healing_432hz_08.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-free-soul-om-mantra-chants-in-two-tones-452178/",
      author: "kalsstockmedia",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: true,
      isActive: true,
      sortOrder: 8,
    ),
    // Nature Sounds - Rain
    MeditationTrack(
      id: "nature_sounds_01",
      label: "Relaxing Rain",
      category: "nature_sounds",
      subCategory: "rain_sounds",
      displayCategory: "Nature Sounds",
      durationSeconds: 765,
      durationLabel: "12:45",
      assetPath: "assets/audio/nature_sounds/nature_sounds_01.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-relaxing-rain-444802/",
      author: "DRAGON-STUDIO",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 9,
    ),
    MeditationTrack(
      id: "nature_sounds_02",
      label: "Gentle Rain 07",
      category: "nature_sounds",
      subCategory: "rain_sounds",
      displayCategory: "Nature Sounds",
      durationSeconds: 90,
      durationLabel: "1:30",
      assetPath: "assets/audio/nature_sounds/nature_sounds_02.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-gentle-rain-07-437321/",
      author: "DRAGON-STUDIO",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 10,
    ),
    MeditationTrack(
      id: "nature_sounds_07",
      label: "Rain Sound and Forest and Nature Sounds",
      category: "nature_sounds",
      subCategory: "rain_sounds",
      displayCategory: "Nature Sounds",
      durationSeconds: 302,
      durationLabel: "5:02",
      assetPath: "assets/audio/nature_sounds/nature_sounds_07.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-rain-sound-and-forest-and-nature-sounds-18259/",
      author: "INNORECORDS (Freesound)",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 11,
    ),
    // Nature Sounds - Ocean / Water
    MeditationTrack(
      id: "nature_sounds_03",
      label: "Ocean Waves",
      category: "nature_sounds",
      subCategory: "ocean_water",
      displayCategory: "Nature Sounds",
      durationSeconds: 71,
      durationLabel: "1:11",
      assetPath: "assets/audio/nature_sounds/nature_sounds_03.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-ocean-waves-250310/",
      author: "RMultimediaEU",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 12,
    ),
    MeditationTrack(
      id: "nature_sounds_04",
      label: "Ocean Waves Sound 01",
      category: "nature_sounds",
      subCategory: "ocean_water",
      displayCategory: "Nature Sounds",
      durationSeconds: 75,
      durationLabel: "1:15",
      assetPath: "assets/audio/nature_sounds/nature_sounds_04.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-ocean-waves-sound-01-321570/",
      author: "RMultimediaEU",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 13,
    ),
    MeditationTrack(
      id: "nature_sounds_06",
      label: "Nature - Gentle Stream and Birds",
      category: "nature_sounds",
      subCategory: "ocean_water",
      displayCategory: "Nature Sounds",
      durationSeconds: 56,
      durationLabel: "0:56",
      assetPath: "assets/audio/nature_sounds/nature_sounds_06.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-nature-gentle-stream-and-birds-401083/",
      author: "RickMagee",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 14,
    ),
    // Nature Sounds - Forest / Wind / Birds
    MeditationTrack(
      id: "nature_sounds_05",
      label: "Relaxing Birds and Piano Music",
      category: "nature_sounds",
      subCategory: "forest_wind_birds",
      displayCategory: "Nature Sounds",
      durationSeconds: 2239,
      durationLabel: "37:19",
      assetPath: "assets/audio/nature_sounds/nature_sounds_05.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-relaxing-birds-and-piano-music-137153/",
      author: "InnerTune",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 15,
    ),
    MeditationTrack(
      id: "nature_sounds_08",
      label: "Wind Whispers with Birds Ambiance",
      category: "nature_sounds",
      subCategory: "forest_wind_birds",
      displayCategory: "Nature Sounds",
      durationSeconds: 125,
      durationLabel: "2:05",
      assetPath: "assets/audio/nature_sounds/nature_sounds_08.mp3",
      sourceUrl: "https://pixabay.com/sound-effects/nature-wind-whispers-with-birds-ambiance-209840/",
      author: "EmpressNefertitiMumbi",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 16,
    ),
    // Ambient - Meditation
    MeditationTrack(
      id: "ambient_atmospheric_01",
      label: "Meditation Ambient",
      category: "ambient_atmospheric",
      subCategory: "ambient_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 306,
      durationLabel: "5:06",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_01.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-meditation-ambient-375361/",
      author: "lunemare",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 17,
    ),
    MeditationTrack(
      id: "ambient_atmospheric_02",
      label: "Ambient Meditation",
      category: "ambient_atmospheric",
      subCategory: "ambient_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 373,
      durationLabel: "6:13",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_02.mp3",
      sourceUrl: "https://pixabay.com/music/ambient-ambient-meditation-485723/",
      author: "QuietPhase",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 18,
    ),
    MeditationTrack(
      id: "ambient_atmospheric_03",
      label: "Meditation",
      category: "ambient_atmospheric",
      subCategory: "ambient_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 186,
      durationLabel: "3:06",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_03.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-meditation-513747/",
      author: "leberch",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 19,
    ),
    MeditationTrack(
      id: "ambient_atmospheric_04",
      label: "Meditation Relaxing Music",
      category: "ambient_atmospheric",
      subCategory: "ambient_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 605,
      durationLabel: "10:05",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_04.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-meditation-relaxing-music-293922/",
      author: "DanaMusic",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 20,
    ),
    // Ambient - Deep Space
    MeditationTrack(
      id: "ambient_atmospheric_05",
      label: "Deep Meditation",
      category: "ambient_atmospheric",
      subCategory: "deep_space_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 646,
      durationLabel: "10:46",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_05.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-deep-meditation-192828/",
      author: "Grand_Project",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 21,
    ),
    MeditationTrack(
      id: "ambient_atmospheric_06",
      label: "Cinematic Space",
      category: "ambient_atmospheric",
      subCategory: "deep_space_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 238,
      durationLabel: "3:58",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_06.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-cinematic-space-510707/",
      author: "leberch",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 22,
    ),
    MeditationTrack(
      id: "ambient_atmospheric_07",
      label: "Calm",
      category: "ambient_atmospheric",
      subCategory: "deep_space_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 210,
      durationLabel: "3:30",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_07.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-calm-509384/",
      author: "leberch",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: true,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 23,
    ),
    // Ambient - Piano
    MeditationTrack(
      id: "ambient_atmospheric_08",
      label: "Piano Dreamcloud Meditation",
      category: "ambient_atmospheric",
      subCategory: "piano_meditation",
      displayCategory: "Ambient & Atmospheric",
      durationSeconds: 913,
      durationLabel: "15:13",
      assetPath: "assets/audio/ambient_atmospheric/ambient_atmospheric_08.mp3",
      sourceUrl: "https://pixabay.com/music/meditationspiritual-piano-dreamcloud-meditation-179215/",
      author: "NaturesEye",
      license: "Pixabay Content License",
      isRoyaltyFree: true,
      contentIdRegistered: false,
      isAiGenerated: false,
      isActive: true,
      sortOrder: 24,
    )
  ];
}
